name: Build Test2

on:
  workflow_dispatch:
  schedule:
    - cron: '10 * * * *' # run every day at 16:20 UTC / 8:20 PST

concurrency:
  group: ${{ github.workflow }}

jobs:
  build1:
  

    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        ref: main
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          7.0.x
    - name: Restore dependencies
      run: dotnet restore src/YouRata.Common/
    - name: Build Test
      run: dotnet build src/YouRata.Common/ --no-restore
    - name: Restore dependencies2
      run: dotnet restore src/YouRata.ConflictMonitor/
    - name: Build Test2
      run: dotnet build src/YouRata.ConflictMonitor/ --no-restore
    - name: Restore dependencies3
      run: dotnet restore src/YouRata.InitialSetup/
    - name: Build Test3
      run: dotnet build src/YouRata.InitialSetup/ --no-restore
    - name: Restore dependencies4
      run: dotnet restore src/YouRata.YouTubeSync/
    - name: Build Test4
      run: dotnet build src/YouRata.YouTubeSync/ --no-restore
    - name: Restore dependencies5
      run: dotnet restore src/YouRata.ActionReport/
    - name: Build Test5
      run: dotnet build src/YouRata.ActionReport/ --no-restore
    - name: Checkout errata repo
      uses: actions/checkout@v3
      with:
        ref: errata
        path: errata-checkout
    - name: Test (I:Debug T:Debug R:false)
      run: dotnet run --verbosity normal --project src/YouRata.ConflictMonitor/YouRata.ConflictMonitor.csproj --no-build src/YouRata.ConflictMonitor/Debug/net7.0/YouRata.ConflictMonitor.dll &
      env:
        ACTION_TOKEN : ${{ secrets.GITHUB_TOKEN }}
        API_TOKEN : ${{ secrets.API_TOKEN }}
        TOKEN_RESPONSE : ${{ secrets.TOKEN_RESPONSE }}
        PROJECT_CLIENT_SECRET : ${{ vars.PROJECT_CLIENT_SECRET }}
        PROJECT_CLIENT_ID : ${{ vars.PROJECT_CLIENT_ID }}
        PROJECT_API_KEY : ${{ secrets.PROJECT_API_KEY }}
    - name: Test2 (I:Debug T:Debug R:false)
      if : ${{ env.INITIAL_SETUP_COMPLETE == 'false' }}
      run: dotnet run --verbosity normal --project src/YouRata.InitialSetup/YouRata.InitialSetup.csproj --no-build src/YouRata.InitialSetup/Debug/net7.0/YouRata.InitialSetup.dll
      env:
        CODE : ${{ secrets.CODE }}
    - name: Test3 (I:Debug T:Debug R:false)
      run: dotnet run --verbosity normal --project src/YouRata.YouTubeSync/YouRata.YouTubeSync.csproj --no-build src/YouRata.YouTubeSync/Debug/net7.0/YouRata.YouTubeSync.dll
    - name: Test4 (I:Debug T:Debug R:false)
      if: success() || failure()
      run: dotnet run --verbosity normal --project src/YouRata.ActionReport/YouRata.ActionReport.csproj --no-build src/YouRata.ActionReport/Debug/net7.0/YouRata.ActionReport.dll
    - name: env
      run: env
